# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizMaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='close_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(null=True),
        ),
    ]
