# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 12:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizMaster', '0004_auto_20170322_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='close_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
